name: mila_kru_reguler
description: "Aplikasi BIS MILA SEJAHTERA Kru Reguler"

version: 1.0.0+11

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  crypto: ^3.0.1
  #  connectivity: ^3.0.6
  intl: ^0.19.0
  path_provider: ^2.0.15
  path_provider_android: ^2.0.27
  pdf: ^3.6.0
  flutter_pdfview: ^1.0.1
  open_file: ^3.0.1
  qr_flutter: ^4.0.0
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.0
  flutter_animate: ^4.3.0
  flutter_cache_manager: ^3.3.1
  font_awesome_flutter: ^10.6.0
  from_css_color: 2.0.0
  google_fonts: ^6.1.0
  json_path: ^0.7.0
  page_transition: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  timeago: ^3.6.0
  url_launcher: ^6.2.1

  blue_thermal_printer: ^1.2.3
  esc_pos_utils: ^1.1.0
  device_info_plus: ^9.0.3

  image: ^3.0.2

  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.2.2

  permission_handler: ^11.1.0
  permission_handler_platform_interface: ^4.0.2

  fluttertoast: ^8.2.2

  shimmer: ^3.0.0

  #  baru
  image_picker: ^0.8.7+3
  #  flutter_image_compress: ^1.1.0

  http: any

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5

  webview_flutter_wkwebview: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mila_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/mila_icon.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_mila.png
    - assets/images/logo_mila.png
    - assets/images/logo_print.png
    - assets/images/icon_mila.png
    - assets/images/logo_mila.png
    - assets/images/mila_logo.png
    - assets/images/mila_icon.png